language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm rebuild node-sass
  - npm i angular-cli-ghpages

script:
  - ng build --prod --base-href "https://extendz.github.io/extendz-live/"

after_success:
  - ngh --repo=https://GITHUB_TOKEN@github.com/extendz/extendz-live.git --name="rumes" --email=rs.kumarasinghe89@gmail.com --dir=dist/app
