language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

script:
  - ng build --prod --base-href "https://extendz.github.io/extendz-live/"

after_success:
  - ngh --repo=https://$GITHUB_TOKEN@github.com/extendz/extendz-live.git --name="rumes" --email=rs.kumarasinghe89@gmail.com --dir=dist/app --no-silent


cache:
  directories:
    - node_modules