language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm rebuild node-sass
  - npm i angular-cli-ghpages

script:
  - ng build --prod --base-href "https://extendz.github.io/extendz-live/"
  - ngh --repo=https://e14f19602c62e3ee9bc399b82a9034e3d6a20eb6@github.com/extendz/extendz-live


notifications:
  email:
    on_failure: change
    on_success: change